//Write a program tto check various data type

#include <stdio.h>
int main()
{
    // int data type  ex: 1,2,3,4...
    // char data type ex: a,b,c,d....
    //float data type ex: 1.2,3.45,5.343....
    //double data type ex: 1.43533...
    return 0;
}